### ISSUE TITLE
Clustering at > 97%

### ISSUE THREAD

**Issue by jcaguayo** [hsgweon/pipits#23]
Hi,
Thank you very much for the pipeline. It is very useful and comfortable to work with a specific pipeline developed for fungi. I have already tested with satisfactory results
I was wondering if you plan to incorporate some options for clustering with VSEARCH, especially an option to cluster at > 97%. This would be awesome for the pipeline.
Thanks a lot again.
Greetings,
Jaime

**Comment by hsgweon** [comment]
Hi @jcaguayo 
Thank you for the kind words.
There is an option for that in pipits_process.
If you type:
`pipits_process -h`
you will see some options, and the one you are looking for is:
`-d 0.97` or `-d 0.98` etc. 

I do wish I have more time to make the program better and there are tons of improvements I want to implement, but this project was never properly funded and I'm having to maintain it "pro bono", so that's been the main difficulty. But do let me know of any issues and I will put those into my TODO list.
