### ISSUE TITLE
Empty read pair list

### ISSUE THREAD

**Issue by lcamVz** [hsgweon/pipits#39]
I just ran the `pispino_createreadpairslist -i rawdata/ -o paired_readlist.txt` and the paired_readlist resulted to be empty? I have my fastq files in the rawdata folder  I don't know what could be happening.

**Comment by hsgweon** [comment]
@lcamVz 
Can you post filenames of the first few files?

**Comment by lcamVz** [comment]
Hi,  thanks for the reply. 

`C10_R1.fq  C10_R2.fq`

Do I need to rename the files?

**Comment by hsgweon** [comment]
Instead of running pispino_createreadpairslist to create your list file, you can manually create your own paired_readlist.txt 


So it could look like this (make sure the gaps are tabs). The order goes: SampleName ForwardSequenceFile ReverseSequenceFile

> C10 C10_R1.fq C10_R2.fq
> C11 C11_R1.fq C11_R2.fq

Then feed this file into the next step in the pipeline.

The other option is to change the filenames which isn't ideal in your case.

**Comment by lcamVz** [comment]
Souds good.  Thanks

> Instead of running pispino_createreadpairslist to create your list file, you can manually create your own paired_readlist.txt
> 
> So it could look like this (make sure the gaps are tabs). The order goes: SampleName ForwardSequenceFile ReverseSequenceFile
> 
> > C10 C10_R1.fq C10_R2.fq
> > C11 C11_R1.fq C11_R2.fq
> 
> Then feed this file into the next step in the pipeline.
> 
> The other option is to change the filenames which isn't ideal in your case.
