### ISSUE TITLE
ITSx and hmmscan speeds

### ISSUE THREAD

**Issue by hleungtc** [hsgweon/pipits#4]
Hi there, I have been trying out the PIPITS pipeline and had a few questions regarding processing speeds. As stated in the PIPITS paper, the pipits_funits step is the computational bottleneck in the pipeline. If I'm not mistaken, ITSx utilizes hmmscan. I did a little bit of research, and it seems that hmmscan is substantially slower than hmmsearch (see URL below). What are your thoughts on this? Do you think it would be possible or worthwhile to use hmmsearch to speed up this step? Apologies if I have overlooked an obvious reason not to do so.

https://cryptogenomicon.org/2011/05/27/hmmscan-vs-hmmsearch-speed-the-numerology/

**Comment by ghost** [comment]
Thanks for that link. Yes I do readily use HMMER for my other projects and hmmsearch is the weapon of choice! Unfortunately ITSx is not something I have developed and the issue needs to be addressed to ITSx developers. The only thing is that the program hasn't been updated since 2014, and while it's a great tool it will be good to get the whole thing updated / re-coded or at least update their HMMER profiles given that fungal db has massively grown over the last few years. I do plan to address the whole issue of speed/library/some cool ideas at some stage but won't be any time soon as there is virtually no funding for the project anymore.

**Comment by hsgweon** [comment]
And sorry that was me using my personal account (rather than work account!)

**Comment by hleungtc** [comment]
Thanks for your insights, I'll keep my fingers crossed for future updates :)
