### ISSUE TITLE
Ion torrent single ended ITS data analysis with PIPITS 

### ISSUE THREAD

**Issue by MarwaElnaiem** [hsgweon/pipits#49]
Dear all, 
@hsgweon 
I would like to know how I could use PIPITS pipeline to analyze my ITS1 data generated by ion torrent PGM? How I can perform prepare the sequences list step?

Marwa

**Comment by hsgweon** [comment]
@MarwaElnaiem 
PIPITS isn't really designed for data generated by Ion Torrent, so I can't really help you here. Especially given that Ion Torrent has different error rates, I am not sure how PIPITS will perform or be sufficiently reliable. 

But if you want to try it anyway, then you will somehow need to prepare your data so that your FASTA file has the following structure, you can run PIPITS_FUNITS and PIPITS_PROCESS.

So, the header should have SampleX followed by an underscore followed by an index:
>SampleA_1
TTAAGTTCAGCGGGTATCCCTACCTGATCCGAGGTCAAACTTAGAAAGTTGGGGGTTGTTGGCCAGTACCACCGAGTCCCTATAGCGAGGATATTTACTACGCTCAGGGCCACGGAGGCACCGCCACTGATTTTAAGGCCTGCCAGGTGAGTGGCAGAGCCCAATACCAAGCTAAGCTTGAGGGTTGTAATGACGCTCGAACAGGCATGCCCCTCGGAATACCAAGGGGCGCAATGTGCGTT
>SampleA_2
TTAAGTTCAGCGGGTATCCCTACCTGATCCGAGGTCAACCTTGTGTGGGGGTTGTATGACGGCGCTTGCCACCCTTCCCTAACAGCGACGAGCATTACTGCGCTGAAGGTCGGACGGCGGCCGCCACTGATTTTGAAGCGAGCCCCGGGTAAGCGGGGCGGGCTCAACACCAAGCAGAGCTTGAGGGTTGTAATGACGCTCGAACAGGCATGCCCCCCGGAATACCAGGGGGCGCAATGTGCGTT
>SampleB_1
TTAAGTTCAGCGGGTATCCCTACCTGATCTGAGGTCAACCTTGTGAAAGATATAGGTGTAGACCGGGTGCCGTCGACCCTTGAGACCGGTACGTGCTCCGTGAAGATGCTCAGTGTACCGGGGGTGCAACAGCCCGCCGTCATTGTCTTTGGGAGGGGTCCAGGGGGGGCCCTGGACCAAACCGTCCAACACCAAGCCGGGGGCTTGAGGGGTGAAAATGACGCTCGAACAGGCATGCCCTTCGGAATACCAAAGGGCGCAATGTGCGTT

**Comment by MarwaElnaiem** [comment]
I though that it could be used with ion torrent as mentioned in the pipeline paper (see the attached image) And i though that may be special options for such data are available. 
I will try it. 
Thanks for reply
![20210726_173604](https://user-images.githubusercontent.com/40704977/127018161-a3fbc808-aa44-41ff-9f6e-e6246504d1f9.jpg)

**Comment by hsgweon** [comment]
@MarwaElnaiem I've used Ion Torrent data with PIPITS quite awhile ago, but the issue was that the sequences had a very high error rate (mostly homopolymers) leading to overestimation of OTUs (although phylotyping sort of helped to solve this issue - well, not fully!). But, if these quality issues can be remedied AND the FASTA file can be somehow formatted as I have mentioned above, data from any other sequencing platform can be used.

That said, as the title of the paper suggests, PIPITS really is a fully automated pipeline for Illumina sequences "An automated pipeline for analyses of fungal internal transcribed spacer (ITS) sequences from the Illumina sequencing platform"

Let me know if you encounter any issues though.
